# Generated by Django 5.0.14 on 2026-04-22 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('image', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('managed_by_si', models.BooleanField(default=True)),
                ('keycloak_client_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'inscription_application',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_sub', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inscription_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organisme',
            fields=[
                ('id_organisme', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid_organisme', models.CharField(blank=True, max_length=64)),
                ('nom_organisme', models.CharField(max_length=500)),
                ('keycloak_slug', models.SlugField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'inscription_organisme',
                'ordering': ['nom_organisme'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('area_code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=500)),
                ('id_type', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'inscription_reserve',
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_sub', models.CharField(db_index=True, max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('legacy_id_role', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscriptions.organisme')),
            ],
            options={
                'db_table': 'inscription_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ReserveReferentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.reserve')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent_decisions', to='inscriptions.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referent_requests', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_reserve_referent_request',
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending_super', 'En attente super-admin'), ('super_rejected', 'Refusé super-admin'), ('pending_apps', 'En attente validateurs applicatifs'), ('provisioning', 'Provisioning Keycloak'), ('completed', 'Terminé'), ('rejected', 'Refusé')], default='pending_super', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password_cipher', models.TextField(blank=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('champs_addi', models.JSONField(blank=True, default=dict)),
                ('reserve_codes', models.JSONField(blank=True, default=list)),
                ('keycloak_user_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscriptions.organisme')),
                ('created_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_origins', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_registration_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending_apps', 'En attente validateurs'), ('completed', 'Terminé'), ('rejected', 'Refusé')], default='pending_apps', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_access_requests', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_additional_access_request',
            },
        ),
        migrations.CreateModel(
            name='AdditionalAccessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inscriptions.additionalaccessrequest')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.application')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_item_decisions', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_additional_access_item',
            },
        ),
        migrations.CreateModel(
            name='AccessRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.application')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inscriptions.registrationrequest')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_decisions', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_access_request_item',
            },
        ),
        migrations.CreateModel(
            name='OrganismeReserveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_links', to='inscriptions.organisme')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisme_links', to='inscriptions.reserve')),
            ],
            options={
                'db_table': 'inscription_organisme_reserve',
                'unique_together': {('organisme', 'reserve')},
            },
        ),
        migrations.CreateModel(
            name='UserApplicationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('revoked', 'Révoqué'), ('pending', 'En attente')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.application')),
                ('source_additional_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to='inscriptions.additionalaccessitem')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to='inscriptions.accessrequestitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_access', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_user_application_access',
                'unique_together': {('user', 'application')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='inscriptions.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_application_admin',
                'unique_together': {('user', 'application')},
            },
        ),
        migrations.CreateModel(
            name='UserReserveLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referent', models.BooleanField(default=False)),
                ('referent_valid', models.BooleanField(default=False)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.reserve')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_links', to='inscriptions.userprofile')),
            ],
            options={
                'db_table': 'inscription_user_reserve_link',
                'unique_together': {('user', 'reserve')},
            },
        ),
    ]
